### ISSUE TITLE
Airlines app hard crash on empty submit

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [wquist/Goshna#1]
Goshna Airlines app crashes (requiring app restart) if submitting an empty form on first page. No user-facing error messages.

Server is also not running - likely cause with missing try-catch.

```
09-03 14:16:36.590 29578-29578/com.example.wquist.goshnaairlines E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.wquist.goshnaairlines, PID: 29578
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
        at android.view.View.performClick(View.java:6294) 
        at android.view.View$PerformClick.run(View.java:24770) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.example.wquist.goshnaairlines.SetupActivity.submit(SetupActivity.java:131)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
        at android.view.View.performClick(View.java:6294) 
        at android.view.View$PerformClick.run(View.java:24770) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by wquist** [comment]
When the app is, just a small toast would appear, but this wouldn't prevent the user from submitting; the crash is due to the unpopulated spinners in the form.

In commits ef2334b5ce7b821fe5aa35fea3cc831b5312aecb and 84c454dc133bb1dbf14baf114649ddecd37c0948 this is resolved by changing the toast to a dialog notifying the connection error and asking to retry.

Without network connection this unfortunately leads to an infinite loop of dialog-retries. I was thinking of redirecting to a splash screen if the user is unable to reconnect after a few tries. The splash screen can have more detailed instructions telling that the user must be in the airport, etc. I  will mock something up soon.

Note that these commits do not force connection retries on "unimportant" communications. For example, the messages view would just show the toast since the view already has a refresh/retry button.
